import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'AI Test Generator — IGCSE Practice Tests',
  description:
    'Generate custom IGCSE practice tests on any topic in seconds. The AI Test Generator creates exam-style multiple choice, short answer, and extended questions with mark schemes.',
  alternates: { canonical: '/ai-generator' },
  openGraph: {
    title: 'AI Test Generator — RevisionCity',
    description:
      'Create unlimited IGCSE practice tests on any topic. Multiple choice, short answer, and extended questions with mark schemes — generated by AI in seconds.',
    url: '/ai-generator',
  },
};

export default function AiGeneratorLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
